-- ==========================================
-- PROJECT: High-Utility Multi-Tool Platform
-- FILE: supabase_schema_master.sql
-- CREATED: June 2026
-- PURPOSE: Single-source of truth for database architecture.
-- ==========================================

-- 1. EXTENSIONS & PREREQUISITES
-- Enabling cryptographic or UUID extensions needed for modern security
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- SECTION A: PUBLIC UTILITY TABLES (LIVE)
-- ==========================================

-- Table 1: Real-Time Social Feed Posts
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    media_url TEXT
);
ALTER TABLE public.posts DISABLE ROW LEVEL SECURITY;

-- Table 2: Real-Time Global Chat Messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    sender TEXT NOT NULL,
    text TEXT NOT NULL
);
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;

-- Table 3: Referral Tracking Logs
CREATE TABLE IF NOT EXISTS public.referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    referrer_username TEXT NOT NULL,
    new_user_ip TEXT DEFAULT 'tracked_client_device' NOT NULL
);
ALTER TABLE public.referrals DISABLE ROW LEVEL SECURITY;

-- Table 4: Custom checkout & alternative payment tickets
CREATE TABLE IF NOT EXISTS public.payments_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    sender_name TEXT NOT NULL,
    payment_method TEXT NOT NULL,
    amount_value TEXT NOT NULL,
    details_or_code TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL
);
ALTER TABLE public.payments_claims DISABLE ROW LEVEL SECURITY;

-- Table 5: Camera Inventory scanned stocks
CREATE TABLE IF NOT EXISTS public.inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    item_barcode TEXT NOT NULL,
    item_name TEXT NOT NULL,
    qty_count INT DEFAULT 1 NOT NULL
);
ALTER TABLE public.inventory_logs DISABLE ROW LEVEL SECURITY;


-- ==========================================
-- SECTION B: AUTHENTICATED USER & CALCULATION TABLES (FUTURE-PROOF)
-- ==========================================

-- Table 6: Unified Users Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    tier TEXT DEFAULT 'free' CHECK (tier IN ('free', 'premium', 'enterprise')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Table 7: Unified Tool Calculations (Uses JSONB for flexible schemas)
CREATE TABLE IF NOT EXISTS public.user_calculations (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    tool_type TEXT NOT NULL, -- e.g., 'pos-receipt', 'dcf-valuation', 'kinematics'
    input_data JSONB NOT NULL, -- Flexible JSON format so schemas can evolve without DDL edits
    output_data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
ALTER TABLE public.user_calculations ENABLE ROW LEVEL SECURITY;

-- Policies for Authenticated calculations
CREATE POLICY "Users can view their own data" 
    ON public.user_calculations FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own data" 
    ON public.user_calculations FOR INSERT 
    WITH CHECK (auth.uid() = user_id);


-- ==========================================
-- SECTION C: USER SYNCHRONIZATION TRIGGER
-- ==========================================

-- Trigger to automatically create a public.users row when a user registers on Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email)
    VALUES (new.id, new.email);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
